package ops.gateway.entities;

import lombok.Data;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestMaster generated by hbm2java
 */
@Entity
@Data
@Table(name = "request_master", catalog = "ops_pay_service")
public class RequestMaster {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "OBJECT_ID", unique = true, nullable = false)
    private Long objectId;

    @Column(name = "ORIGINAL_TRANS_ID", length = 100)
    private String originalTransId;

    @Column(name = "MAKER_REQUEST_ID", nullable = false, length = 100)
    private String makerRequestId;

    @Column(name = "MAKER_ID", nullable = false)
    private long makerId;


    @Column(name = "MAKER_NAME", length = 150)
    private String makerName;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MAKED_TIME", length = 19)
    private Date makedTime;

    @Column(name = "TRANSACTION_TYPE", nullable = false, length = 50)
    private String transactionType;

   @Column(name = "ACTION_TYPE", nullable = false, length = 50)
    private String actionType;

    @Column(name = "DATA", nullable = false, length = 65535)
    private String data;

    @Column(name = "CHECKER_ID")
    private Long checkerId;

    @Column(name = "CHECKER_NAME", length = 150)
    private String checkerName;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CHECKED_TIME", length = 19)
    private Date checkedTime;

    @Column(name = "STATUS", nullable = false, length = 8)
    private String status;

    @Column(name = "RESULT", nullable = false, length = 10)
    private String result;

    @Column(name = "COMMENT", length = 65535)
    private String comment;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "RESPONSE_TIME", length = 19)
    private Date responseTime;

    @Column(name = "RESPONSE_TRANS_ID", length = 100)
    private String responseTransId;

}
